version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "✅ Install phase started..."

  pre_build:
    commands:
      - echo "✅ Installing dependencies..."
      - pip install -r simple-python-app/requirements.txt
      - echo "✅ Logging into DockerHub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

  build:
    commands:
      - echo "✅ Build phase started..."
      - cd simple-python-app
      - echo "✅ Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
      - echo "✅ Pushing Docker image to registry..."
      - docker push "$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"

  post_build:
    commands:
      - echo "✅ Build completed successfully!"
      - echo "✅ Docker image pushed to DockerHub ✅"

artifacts:
  files:
    - '**/*'
  base-directory: simple-python-app
